# Site settings
baseURL = "https://yimin.io"
languageCode = "en-US"
title = "Yimin Wu"
theme = "gardenias"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2018 Yimin"

[params]

  # Metadata for search engines and social sharing
  author = "yimin"
  description = "My Profile Site"
  shareImage = "images/social.jpg"
  twitterHandle = "onepagelove"

  # Favicon
  favicon = "yimin.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "https://s.yimg.com/uy/build/images/sohp/womens-month-mar-2018/patriciaware_takingabow.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Blog"
        url = "https://diveintoprogramming.com"

      [[params.links.list1.link]]
        text = "Streams"
        url = "https://skydaydayblue.com"

      [[params.links.list1.link]]
        text = "Amazing-x"
        url = "https://amzing-x.com"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "Twitter"
        url = "https://twitter.com/gardenias_wu"

      [[params.links.list2.link]]
        text = "GitHub"
        url = "https://github.com/gardenias"

      [[params.links.list2.link]]
       text = "TaskCreek"
       url = "https://taskcreek.com"


